services:
    ytdlp:
        build: .
        container_name: ytdlp
        volumes:
            - /Users/nicolaserramuspe/Development/linux1/shared:/shared
        stdin_open: true
        tty: true
